# Automatically generated by configure - do not modify
SRC_PATH=/root/ATFF/AFLplusplus/nyx_mode/QEMU-Nyx/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
