/* Automatically generated by create_config - do not modify */
#define TARGET_AARCH64 1
#define TARGET_NAME "aarch64"
#define TARGET_ARM 1
#define TARGET_SYSTBL_ABI common,oabi
#define CONFIG_SOFTMMU 1
#define TARGET_SUPPORTS_MTTCG 1
