/* Automatically generated by create_config - do not modify */
#define TARGET_SPARC64 1
#define TARGET_NAME "sparc64"
#define TARGET_SPARC 1
#define TARGET_SYSTBL_ABI common,64
#define TARGET_ALIGNED_ONLY 1
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_SOFTMMU 1
