/* Automatically generated by create_config - do not modify */
#define TARGET_ABI_MIPSO32 1
#define TARGET_MIPS 1
#define TARGET_NAME "mipsel"
#define TARGET_MIPS 1
#define TARGET_SYSTBL_ABI o32
#define TARGET_ALIGNED_ONLY 1
#define CONFIG_SOFTMMU 1
#define TARGET_SUPPORTS_MTTCG 1
